version: '3.8'

services:
  # Usługa dla backendu Django
  backend:
    build: ./be
    container_name: django_backend
    ports:
      - "8001:8000" # <--- ZMIANA TUTAJ
    volumes:
      - ./be:/app
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

  # Usługa dla frontendu Next.js
  frontend:
    build: ./fe
    container_name: nextjs_frontend
    ports:
      - "3000:3000" # Ten port pozostaje bez zmian
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      # WAŻNE: To ustawienie pozostaje BEZ ZMIAN!
      - NEXT_PUBLIC_API_URL=http://backend:8000/api 
    depends_on:
      - backend