# Generated by Django 5.1.7 on 2025-04-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa inicjatywy')),
                ('acronym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Akronim')),
                ('implementing_entity_name', models.CharField(max_length=255, verbose_name='Nazwa podmiotu wdrażającego')),
                ('entity_status', models.CharField(choices=[('NGO', 'Organizacja pozarządowa (NGO)'), ('BUSINESS', 'Przedsiębiorstwo'), ('UNIVERSITY', 'Uczelnia'), ('LOCAL_GOVT', 'Jednostka samorządu terytorialnego (JST)'), ('OTHER', 'Inne')], max_length=20, verbose_name='Statut podmiotu wdrażającego')),
                ('implementation_area', models.CharField(choices=[('INTERNATIONAL', 'Międzynarodowy'), ('NATIONAL', 'Krajowy'), ('REGIONAL', 'Regionalny'), ('LOCAL', 'Lokalny')], max_length=20, verbose_name='Obszar wdrażania')),
                ('location_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='Miejsce realizacji (kraj/region/miejscowość)')),
                ('implementing_entity_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Strona WWW podmiotu wdrażającego')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Opis inicjatywy (do 1000 znaków)')),
                ('timing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Termin realizacji')),
                ('funding_source', models.CharField(choices=[('PUBLIC', 'Publiczne'), ('PRIVATE', 'Prywatne')], max_length=10, verbose_name='Źródło finansowania')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Strona internetowa inicjatywy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='initiatives', to='initiatives.tag', verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Inicjatywa',
                'verbose_name_plural': 'Inicjatywy',
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
